### ISSUE TITLE
Anchor/marker might be rendered on the wrong row/page

### ISSUE THREAD

**Issue by joeha480** [joeha480/dotify#190] opened 2016-03-24 14:35 UTC
For the following events:
```
<leader><text><marker><text>
```
If the first text event doesn't fit on the current row, the marker will not be rendered on the row where the shift between the first and second text segment takes place. This is important if the transition row is pushed to the following page.

@bertfrees Would you have a look, as this bug was introduced with the fix for #120

**Comment by joeha480** [comment] 2016-03-24 15:14
I added a test to verify:
https://github.com/joeha480/dotify/commit/65d07172bd16862991c2ab78694e422b8a4ed153

**Comment by bertfrees** [comment] 2016-03-25 10:20
OK, I see what the problem is, didn't think of that.

**Comment by bertfrees** [comment] 2016-03-25 10:20
OK please assign to me.

**Comment by bertfrees** [comment] 2016-05-30 16:50
OK I fixed the bug.

**Closed** 2016-06-01 10:20 UTC
Labels: bug
